// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARLkNZHJT_40LOK_FkTT6Cf5s4y9OnfFI',
    appId: '1:58625179922:web:9f95ff2ddeb21e1c8bf3cb',
    messagingSenderId: '58625179922',
    projectId: 'twitterclone-b46a6',
    authDomain: 'twitterclone-b46a6.firebaseapp.com',
    storageBucket: 'twitterclone-b46a6.appspot.com',
    measurementId: 'G-0MRM5RC507',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIwCgWzWFTqr2s_yjSJVspARkt3o_kUmI',
    appId: '1:58625179922:android:78b3d8d36d1b237e8bf3cb',
    messagingSenderId: '58625179922',
    projectId: 'twitterclone-b46a6',
    storageBucket: 'twitterclone-b46a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeKIk8W7j13WUazmOOIenwf73nmsZkR5o',
    appId: '1:58625179922:ios:c8af213534da5c3b8bf3cb',
    messagingSenderId: '58625179922',
    projectId: 'twitterclone-b46a6',
    storageBucket: 'twitterclone-b46a6.appspot.com',
    iosClientId: '58625179922-dhh6qriuaocr5j6tfdf3cm6cv3r3igvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeKIk8W7j13WUazmOOIenwf73nmsZkR5o',
    appId: '1:58625179922:ios:c8af213534da5c3b8bf3cb',
    messagingSenderId: '58625179922',
    projectId: 'twitterclone-b46a6',
    storageBucket: 'twitterclone-b46a6.appspot.com',
    iosClientId: '58625179922-dhh6qriuaocr5j6tfdf3cm6cv3r3igvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterclone',
  );
}
